# config

# interval in seconds
interval: 60

# BBDC Login
login:
  username: "YOUR_BBDC_ID"
  password: "YOUR_BBDC_PASSWORD"

# preferred months and session E.g. [] or ["202306", "202307"] -> sessions: [3, 4, 5, 6, 7]
# You can also use a dictionary to specify different sessions for weekdays and weekends:
# sessions:
#   weekday: [7]
#   weekend: [3, 4]
pref: 
  months: ["202604", "202605"]
  sessions: [3, 4, 5, 6, 7]

# manually solve captchas?
captcha:
  login: False
  booking: False

# OCR space API (for automatically solving captchas accurately)
ocr:
  api_key: "K82590680388957" # Free default test key from OCR.space


enable_booking: True

telegram:
  enabled: False
  token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "YOUR_TELEGRAM_CHAT_ID"

discord:
  enabled: False
  webhook:  "YOUR_DISCORD_WEBHOOK_URL"